"""SMTP email delivery — no third-party SDK."""

import logging
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

import config

logger = logging.getLogger(__name__)


def send_email(
    to: str | list[str],
    subject: str,
    body_html: str,
    body_text: str | None = None,
) -> bool:
    """Send an email via SMTP.

    Args:
        to: Recipient address or list of addresses.
        subject: Email subject line.
        body_html: HTML body content.
        body_text: Plain-text fallback (auto-stripped from HTML if not provided).

    Returns:
        True on success, False on failure (error is logged).
    """
    if not config.SMTP_HOST:
        logger.warning("SMTP not configured — skipping email to %s", to)
        return False

    recipients = [to] if isinstance(to, str) else to

    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"] = config.NOTIFICATION_FROM_EMAIL
    msg["To"] = ", ".join(recipients)

    if body_text:
        msg.attach(MIMEText(body_text, "plain"))
    msg.attach(MIMEText(body_html, "html"))

    try:
        with smtplib.SMTP(config.SMTP_HOST, config.SMTP_PORT) as server:
            server.ehlo()
            server.starttls()
            server.login(config.SMTP_USER, config.SMTP_PASSWORD)
            server.sendmail(config.NOTIFICATION_FROM_EMAIL, recipients, msg.as_string())
        logger.info("Email sent to %s: %s", recipients, subject)
        return True
    except smtplib.SMTPException as exc:
        logger.error("Failed to send email to %s: %s", recipients, exc)
        return False


def send_alert(
    account_name: str,
    anomaly_type: str,
    severity: str,
    campaign_name: str,
    diagnosis: str,
    recommended_action: str,
    alert_email: str,
) -> bool:
    """Send an anomaly alert email."""
    subject = f"[{severity}] Google Ads Alert — {account_name}: {anomaly_type.replace('_', ' ').title()}"

    body_html = f"""
    <html><body style="font-family: Arial, sans-serif; max-width: 600px; margin: auto;">
    <h2 style="color: {'#d32f2f' if severity in ('CRITICAL','HIGH') else '#f57c00'};">
        {severity} Alert — {account_name}
    </h2>
    <table style="width:100%; border-collapse: collapse;">
        <tr><td style="padding:8px; font-weight:bold; background:#f5f5f5;">Campaign</td>
            <td style="padding:8px;">{campaign_name}</td></tr>
        <tr><td style="padding:8px; font-weight:bold; background:#f5f5f5;">Anomaly Type</td>
            <td style="padding:8px;">{anomaly_type.replace('_', ' ').title()}</td></tr>
        <tr><td style="padding:8px; font-weight:bold; background:#f5f5f5;">Severity</td>
            <td style="padding:8px;">{severity}</td></tr>
    </table>
    <h3>Diagnosis</h3>
    <p>{diagnosis}</p>
    <h3>Recommended Action</h3>
    <p>{recommended_action}</p>
    <hr>
    <p style="color:#999; font-size:12px;">
        Generated by CloudIA Google Ads Agent System.
        Review and approve actions at your dashboard.
    </p>
    </body></html>
    """

    body_text = (
        f"{severity} ALERT — {account_name}\n"
        f"Campaign: {campaign_name}\n"
        f"Type: {anomaly_type}\n\n"
        f"Diagnosis:\n{diagnosis}\n\n"
        f"Recommended Action:\n{recommended_action}"
    )

    return send_email(
        to=alert_email,
        subject=subject,
        body_html=body_html,
        body_text=body_text,
    )


def send_queue_summary(
    account_name: str,
    decisions: list[dict],
    alert_email: str,
) -> bool:
    """Send a summary of new approval queue items."""
    count = len(decisions)
    subject = f"[Action Required] {count} Google Ads recommendation{'s' if count != 1 else ''} — {account_name}"

    rows_html = "".join(
        f"<tr><td style='padding:8px;border-bottom:1px solid #eee;'>{d.get('action_type','')}</td>"
        f"<td style='padding:8px;border-bottom:1px solid #eee;'>{d.get('target_name','')}</td>"
        f"<td style='padding:8px;border-bottom:1px solid #eee;'>{d.get('reasoning','')[:120]}...</td></tr>"
        for d in decisions
    )

    body_html = f"""
    <html><body style="font-family: Arial, sans-serif; max-width: 700px; margin: auto;">
    <h2>Google Ads Recommendations — {account_name}</h2>
    <p>{count} new recommendation{'s' if count != 1 else ''} ready for your review.</p>
    <table style="width:100%; border-collapse: collapse; margin-top:16px;">
        <thead>
            <tr style="background:#1565c0; color:white;">
                <th style="padding:10px; text-align:left;">Action</th>
                <th style="padding:10px; text-align:left;">Target</th>
                <th style="padding:10px; text-align:left;">Reasoning</th>
            </tr>
        </thead>
        <tbody>{rows_html}</tbody>
    </table>
    <p style="margin-top:24px;">Log in to your dashboard to approve or reject these recommendations.</p>
    <hr>
    <p style="color:#999; font-size:12px;">CloudIA Google Ads Agent System</p>
    </body></html>
    """

    return send_email(to=alert_email, subject=subject, body_html=body_html)


def send_weekly_report(
    account_name: str,
    report: dict,
    report_email: str,
) -> bool:
    """Send a formatted weekly performance report email."""
    subject = f"Weekly Google Ads Report — {account_name}"

    wins_html = "".join(f"<li>✓ {w}</li>" for w in report.get("key_wins", []))
    concerns_html = "".join(f"<li>⚠ {c}</li>" for c in report.get("areas_of_concern", []))
    recs_html = "".join(f"<li>{r}</li>" for r in report.get("recommendations", []))

    top_campaigns_html = "".join(
        f"<tr><td style='padding:8px;border-bottom:1px solid #eee;'>{c.get('campaign_name','')}</td>"
        f"<td style='padding:8px;border-bottom:1px solid #eee;'>{c.get('performance_summary','')}</td>"
        f"<td style='padding:8px;border-bottom:1px solid #eee;'>{c.get('notable_metric','')}</td></tr>"
        for c in report.get("top_campaigns", [])
    )

    body_html = f"""
    <html><body style="font-family: Arial, sans-serif; max-width: 700px; margin: auto;">
    <h2>Weekly Google Ads Report — {account_name}</h2>
    <h3>Executive Summary</h3>
    <p>{report.get('executive_summary', '')}</p>
    <h3>Key Wins</h3><ul>{wins_html}</ul>
    <h3>Areas of Concern</h3><ul>{concerns_html}</ul>
    <h3>Top Campaigns</h3>
    <table style="width:100%; border-collapse:collapse;">
        <thead>
            <tr style="background:#1565c0; color:white;">
                <th style="padding:10px; text-align:left;">Campaign</th>
                <th style="padding:10px; text-align:left;">Summary</th>
                <th style="padding:10px; text-align:left;">Notable Metric</th>
            </tr>
        </thead>
        <tbody>{top_campaigns_html}</tbody>
    </table>
    <h3>Recommendations</h3><ol>{recs_html}</ol>
    <hr>
    <p style="color:#999; font-size:12px;">CloudIA Google Ads Agent System</p>
    </body></html>
    """

    return send_email(to=report_email, subject=subject, body_html=body_html)
