"""Pydantic v2 request/response schemas for all API routes.

All response schemas use ConfigDict(from_attributes=True) so that SQLAlchemy
ORM instances can be passed directly to FastAPI's response_model serialiser.
"""

from datetime import datetime
from typing import Any

from pydantic import BaseModel, ConfigDict, Field


# ── Request schemas ────────────────────────────────────────────────────────────


class CampaignBriefRequest(BaseModel):
    """Body for POST /campaigns/create.

    Encapsulates the human-authored brief that the Creator agent uses to
    generate a complete campaign structure.
    """

    account_id: int = Field(..., description="Primary key of the Account to create the campaign for.")
    brief: "CampaignBriefDetail" = Field(..., description="Structured campaign brief.")


class CampaignBriefDetail(BaseModel):
    """The nested brief object inside CampaignBriefRequest."""

    goal: str = Field(
        ...,
        description="High-level campaign goal, e.g. 'increase leads', 'drive e-commerce sales'.",
    )
    product_service: str = Field(
        ...,
        description="What product or service is being advertised.",
    )
    audience_description: str = Field(
        ...,
        description="Description of the target audience.",
    )
    budget_daily_zar: float = Field(
        ...,
        gt=0,
        description="Daily budget in South African Rand.",
    )
    geo_targets: list[str] = Field(
        default_factory=list,
        description="List of geographic target names, e.g. ['Johannesburg', 'Cape Town'].",
    )
    languages: list[str] = Field(
        default_factory=list,
        description="List of language names, e.g. ['English', 'Afrikaans'].",
    )
    landing_page_url: str = Field(
        ...,
        description="The destination URL ads in this campaign will point to.",
    )


# Rebuild CampaignBriefRequest after CampaignBriefDetail is defined
CampaignBriefRequest.model_rebuild()


class QueueActionRequest(BaseModel):
    """Body for POST /queue/{item_id}/approve and POST /queue/{item_id}/reject."""

    reviewed_by: str = Field(
        ...,
        description="Identifier of the human reviewer (email address or username).",
    )


class BaselineRequest(BaseModel):
    """Body for POST /accounts/{account_id}/baseline.

    All fields are optional — only the supplied values will be updated.
    """

    ctr: float | None = Field(None, ge=0, le=1, description="Baseline click-through rate (0–1).")
    cvr: float | None = Field(None, ge=0, le=1, description="Baseline conversion rate (0–1).")
    cpc: float | None = Field(None, ge=0, description="Baseline cost-per-click in ZAR.")
    cpa: float | None = Field(None, ge=0, description="Baseline cost-per-acquisition in ZAR.")
    roas: float | None = Field(None, ge=0, description="Baseline return on ad spend.")


# ── Response schemas ───────────────────────────────────────────────────────────


class AccountResponse(BaseModel):
    """Serialised Account row returned by GET /accounts and related routes."""

    model_config = ConfigDict(from_attributes=True)

    id: int
    client_name: str
    customer_id: str
    status: str
    industry: str | None = None
    primary_kpi: str | None = None
    primary_kpi_target: float | None = None


class QueueItemResponse(BaseModel):
    """Serialised ApprovalQueue row returned by queue-related routes."""

    model_config = ConfigDict(from_attributes=True)

    id: int
    account_id: int
    agent_name: str
    action_type: str
    action_payload: dict[str, Any] | None = None
    reasoning: str | None = None
    status: str
    created_at: datetime
    reviewed_at: datetime | None = None
    reviewed_by: str | None = None


class CreateCampaignResponse(BaseModel):
    """Response for POST /campaigns/create.

    Returns the queue item ID so the caller can track its approval status,
    plus the full campaign structure that Claude generated.
    """

    queue_item_id: int = Field(..., description="Primary key of the pending ApprovalQueue row.")
    status: str = Field(..., description="Queue item status — always 'pending' on creation.")
    campaign_structure: dict[str, Any] = Field(
        ...,
        description="Full campaign structure as generated by Claude "
                    "(campaign_name, campaign_settings, ad_groups).",
    )


class AuditLogResponse(BaseModel):
    """Serialised AuditLog row returned by GET /audit."""

    model_config = ConfigDict(from_attributes=True)

    id: int
    account_id: int
    campaign_id: str | None = None
    anomaly_type: str | None = None
    severity: str | None = None
    diagnosis: str | None = None
    recommended_action: str | None = None
    run_time: datetime
    acknowledged: bool
